### ISSUE TITLE
bug in notebook 5: missing anon=True in s3

### ISSUE THREAD

**Issue by murphyk** [saturncloud/workshop-dask-pytorch#3]
In [notebook 5](https://github.com/saturncloud/workshop-dask-pytorch/blob/main/transfer_learning_demo/05-transfer-prepro.ipynb), cell 'Optional: Checking Data Labels', this line fails
```
s3 = s3fs.S3FileSystem()

with s3.open('s3://saturn-public-data/dogs/imagenet1000_clsidx_to_labels.txt') as f:
    imagenetclasses = [line.strip() for line in f.readlines()]
```
but can be fixed using
```
s3 = s3fs.S3FileSystem(anon=True)
```

**Comment by skirmer** [comment]
Thanks for the catch! We'll update the notebooks.

**Comment by murphyk** [comment]
Thanks. Please ping me when they are ready, I will try them again.
