### ISSUE TITLE
setup2.py hard-codes nworkers=3 and thus breaks notebook 6a when nworkers != 3

### ISSUE THREAD

**Issue by murphyk** [saturncloud/workshop-dask-pytorch#4]
In [noteboook 6a](https://github.com/saturncloud/workshop-dask-pytorch/blob/main/transfer_learning_demo/06a-transfer-training-s3.ipynb), you write ```%run -i ../tools/setup2.py``` to emulate running notebook 5. This just hung for me, until I realized that  it contained the line ```client.wait_for_workers(3)```, which does not work for me, since I am running the demo with nworkers=1 (to avoid $5/hr limit for free trial).

**Comment by skirmer** [comment]
Sorry, that's a good point. These notebooks were for our workshop, and we didn't think of that issue. I see you put in a request to bump your limit, so that should help.
